version: 2
updates:
  # Bundler Configuration
  - package-ecosystem: "bundler"
    directory: "/"
    labels:
      - "gem"
      - "dependencies"
    schedule:
      interval: "daily"

  # NPM Package Configuration
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "daily"