version: 2.1

# Definition of environments where jobs will be executed
executors:
  # Ruby environment
  ruby-on-rails:
    # Jobs will be run in a docker container
    docker:
      # Ruby + Node + Selenium environment (ideal for testing)
      - image: cimg/ruby:3.1.2-browsers
        # Reference: https://circleci.com/docs/language-ruby
        environment:
          PARALLEL_WORKERS: "1"
          # Bundler Configuration
          # ---------------------
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          # Disable changes in Gemfile
          BUNDLE_FROZEN: true
          # Database Configuration
          # ----------------------
          PGHOST: 127.0.0.1
          PGUSER: albert-ci
          PGPASSWORD: ""
          # Rails environment Configuration
          # -------------------------------
          RAILS_ENV: test

      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: albert-ci
          POSTGRES_DB: Albert_Template_test
          POSTGRES_PASSWORD: ""

jobs:
  install-npm-packages:
    working_directory: ~/app
    executor: ruby-on-rails
    steps:
      - checkout
      - restore_cache:
          name: Restore npm packages cache
          keys:
            - yarn-cache-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v4-{{ .Branch }}
            - yarn-cache-v4-
      - run:
          name: Install npm packages if not cached
          command: |
            yarn install --ignore-engines --frozen-lockfile
      - save_cache:
          name: Save installed npm packages in cache
          paths:
            - ~/.cache/yarn
          key: yarn-cache-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}

  install-ruby-gems:
    working_directory: ~/app
    executor: ruby-on-rails
    steps:
      - checkout
      - restore_cache:
          name: Restore gems cache
          keys:
            - gem-cache-v4-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v4-{{ .Branch }}
            - gem-cache-v4-
      - run:
          name: Install gems if not cached
          command: |
            gem install bundler
            bundle check || bundle install --jobs=6 --retry=3 --path vendor/bundle
      - save_cache:
          name: Save installed gems in cache
          paths:
            - vendor/bundle
          key: gem-cache-v4-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

  configure-database:
    working_directory: ~/app
    executor: ruby-on-rails
    steps:
      - run:
          name: Set up DB
          command: bundle exec rails db:drop db:create db:structure:load --trace
      - run:
          name: Load DB fixtures
          command: bundle exec rails db:test:prepare

  run-tests:
    working_directory: ~/app
    executor: ruby-on-rails
    steps:
      - run:
          name: Run all tests
          command: bundle exec rails test:all

# Definition of workflows
workflows:
  # Run application test suite
  run_tests:
    jobs:
      - install-ruby-gems
      - install-npm-packages
      - configure-database:
          requires:
            - install-ruby-gems
            - install-npm-packages
      - run-tests:
          requires:
            - configure-database
